### ISSUE TITLE
The interpreter can't run the Fibonacci code correctly

### ISSUE THREAD

**Issue by 0x61nas** [anas-elgarhy/bfy#10]
The interpreter cannot correctly run the Fibonacci sequence code added in #9, as it enters the infinite loop and prints an infinite number of numbers

**Comment by nibble-4bits** [comment]
Hi @0x61nas! I stumbled upon this repo and this issue while looking for issues to tackle for this year's Hacktoberfest :P

Isn't this the correct behavior of the program though?

Other Brainfuck interpreters such as [this one](https://copy.sh/brainfuck/) or [this other one](https://minond.xyz/brainfuck/) show the same behavior. The program will never terminate, as it will keep computing Fibonacci numbers.

**Comment by 0x61nas** [comment]
> Other Brainfuck interpreters such as [this one](https://copy.sh/brainfuck/) or [this other one](https://minond.xyz/brainfuck/) show the same behavior. The program will never terminate, as it will keep computing Fibonacci numbers.

as I remember it ran normally on [brainfuck-visualizer](https://github.com/usaikiran/brainfuck-visualizer) when I tried it

**Comment by nibble-4bits** [comment]
Found this link: https://brainfuck.org/fib.b. The comments in the file state that the program doesn't terminate and it's the same exact code from #9.

Your interpreter is working correctly

**Comment by 0x61nas** [comment]
huh, now I can't find an excuse for me to open this issue, thanks
